def chart = api.newChartBuilder()
	.newScatter()
		.getOptions()
			.setTitle('')
			.setHideLegend(false)
			.setHideTooltips(false)
			.setSubtitle('')
			.back()
		.addSeries()
			.setLabel('Quantity Vs Discount')
			.setDatamart('DM.Transaction')
			.setCurrency('EUR')
			.addDimFilter('InvoiceDateYear', input.Year as String)
			.setAxisX('Quantity')
				.withTotal()
				.back()
			.setAxisY('Discount')
				.withPercent()
				.back()
			.setAggregationBy('CustomerId')
			.setBandBy('Region')
			.setShowBandByLegend(false)
			.setGeneratedQueryDto('{"datamart":"DM.Transaction","source":"DM.Transaction","name":null,"label":"Quantity vs Discount","rollup":true,"projections":{"x":{"alias":"x","label":"∑Quantity","expression":"SUM({field})","name":"Quantity","advancedProjection":true,"function":null,"default":null,"formatString":"∑{field}","parameters":{"field":"Quantity","quantity":"Quantity","base":"ListPrice"}},"y":{"alias":"y","label":"∑Discount/ƒList Price (%)","expression":"100*SUM({field})/SUM({base})","name":"Discount","advancedProjection":true,"function":null,"default":null,"formatString":"∑{field}/ƒ{base} (%)","parameters":{"field":"Discount","quantity":"Quantity","base":"ListPrice"}},"groupBy":{"alias":"groupBy","label":"Customer Id","expression":"CustomerId"},"bandBy":{"alias":"bandBy","label":"Region","expression":"Region"}},"filter":null,"aggregateFilter":null,"sortBy":[],"options":{"currency":"EUR","discretization":["x","y"],"distribution":["x","y"],"regression":["y","x"]}}')
			.back()
		.getDictionary()
			.buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","key":"groupBy","sectionLabel":"Quantity vs Discount","categoryLabel":"Projection","keyLabel":"Aggregation By","defaultValue":"Customer Id"},{"sectionIdx":1,"category":"PROJECTION","key":"bandBy","sectionLabel":"Quantity vs Discount","categoryLabel":"Projection","keyLabel":"Band By","defaultValue":"Region"},{"sectionIdx":1,"category":"PROJECTION","key":"x","sectionLabel":"Quantity vs Discount","categoryLabel":"Projection","keyLabel":"X Axis","defaultValue":"∑Quantity"},{"sectionIdx":1,"category":"PROJECTION","key":"y","sectionLabel":"Quantity vs Discount","categoryLabel":"Projection","keyLabel":"Y Axis","defaultValue":"∑Discount/ƒList Price (%)"}]')
			.back()
		.build()

return chart