def controller = api.newController()

controller.addHTML("<h2>Links</h2>")
controller.addLink('All Quotes', AppPages.QC_DETAILS_PAGE, null)
controller.addHTML("<h2>Quotes</h2>")
controller.addHTML("<p>The button below will open up the quotes detail page, which lists all the quotes.</p>")
controller.addButton('Open Quotes', AppPages.QC_DETAILS_PAGE, null)
controller.addHTML("""<p>And here is a link that will bring you to an <a href="https://pricefx.vercel.app">external page</a>.</p>""")

controller.addHTML("<h2>All Links</h2>")
controller.addLink("Scatter Charts", AppPages.PA_CHART_SCATTER_PAGE, null)
controller.addLink("Time Series Scatter", AppPages.PA_CHART_TIMESCATTER_PAGE, null)
controller.addLink("Waterfall Charts", AppPages.PA_CHART_WATERFALL_PAGE, null)
controller.addLink("Waterfall Comparison Charts", AppPages.PA_CHART_COMPARISONWF_PAGE, null)
controller.addLink("Bubble Charts", AppPages.PA_CHART_BUBBLE_PAGE, null)
controller.addLink("Bar & Line Charts", AppPages.PA_CHART_BARLINE_PAGE, null)
controller.addLink("Time Series Charts", AppPages.PA_CHART_TIMESERIES_PAGE, null)
controller.addLink("Detailed Time Series Charts", AppPages.PA_CHART_DETAILEDTIME_PAGE, null)
controller.addLink("Histograms", AppPages.PA_CHART_HISTOGRAM_PAGE, null)
controller.addLink("Box Plots", AppPages.PA_CHART_BOXPLOT_PAGE, null)
controller.addLink("Heatmaps", AppPages.PA_CHART_HEATMAP_PAGE, null)
controller.addLink("Data Tables", AppPages.PA_CHART_DATATABLE_PAGE, null)
controller.addLink("Claims", AppPages.CM_MAIN_PAGE, null)
controller.addLink("Claim Records", AppPages.CM_RECORDS_PAGE, null)
controller.addLink("Claim Types", AppPages.CM_TYPES_PAGE, null)
controller.addLink("Configuration Wizards Admin", AppPages.CONFIG_WIZARDS_PAGE, null)
controller.addLink("Dashboard", AppPages.DB_DASHBOARDS_PAGE, null)
controller.addLink("Deal Plans", AppPages.DP_PAGE, null)
controller.addLink("Deal Plan Types", AppPages.DP_TYPES_PAGE, null)
controller.addLink("Bill of Material", AppPages.MD_BOM_PAGE, null)
controller.addLink("Product Competition", AppPages.MD_COMPETITION_PAGE, null)
controller.addLink("Customers", AppPages.MD_CUSTOMERS_PAGE, null)
controller.addLink("Customer Extensions", AppPages.MD_CX_PAGE, null)
controller.addLink("Data Change Requests", AppPages.MD_DCR_PAGE, null)
controller.addLink("Lookup Tables", AppPages.MD_PP_PAGE, null)
controller.addLink("Products", AppPages.MD_PRODUCTS_PAGE, null)
controller.addLink("Product Extensions", AppPages.MD_PX_PAGE, null)
controller.addLink("Wizard", AppPages.MD_WIZARD_PAGE, null)
controller.addLink("Charts", AppPages.PA_CHART_PAGE, null)
controller.addLink("Pie Charts", AppPages.PA_CHART_PIE_PAGE, null)
controller.addLink("Data Sources", AppPages.PA_DATASOURCES_PAGE, null)
controller.addLink("Rollups", AppPages.PA_ROLLUPS_PAGE, null)
controller.addLink("Live Price Lists", AppPages.PB_LPG_PAGE, null)
controller.addLink("Maual Price Lists", AppPages.PB_MPL_PAGE, null)
controller.addLink("Price Lists", AppPages.PB_PL_PAGE, null)
controller.addLink("Price List Simulations", AppPages.PB_SIMULATION_PAGE, null)
controller.addLink("Contracts", AppPages.PM_CONTRACTS_PAGE, null)
controller.addLink("Quotes", AppPages.QC_DETAILS_PAGE, null)
controller.addLink("Quote Types", AppPages.QC_TYPES_PAGE, null)
controller.addLink("Rebate Agreements", AppPages.RM_DETAILS_PAGE, null)
controller.addLink("Rebate Main Page", AppPages.RM_MAIN_PAGE, null)
controller.addLink("Rebate Records", AppPages.RM_RECORDS_PAGE, null)
controller.addLink("Rebate Agreement Templates", AppPages.RM_TEMPLATES_PAGE, null)


return controller